name: Build and Deploy

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          # Add your build commands here

  deployment:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        target: [dev, stage, prod ]
    uses: ./.github/workflows/deployment.yml
    with:
      target-env: ${{ matrix.target }}
    secrets: inherit

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev    

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Dev
        run: |
          # Add your deployment script or commands for the dev environment

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: stage
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Staging
        run: |
          # Add your deployment script or commands for the staging environment

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: prod    

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          # Add your deployment script or commands for the production environment
